# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

  runs-on: ubuntu-latest

  env:
      Solution_Name: ReverseSolution.sln
      Test_Project_Path: Reverse.Tests\Reverse.Tests.csproj

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name
    - name: Build
      run: dotnet build $env:Solution_Name --no-restore 
    - name: Test
      run: dotnet test $env:Test_Project_Path --no-build --verbosity normal
